redis:
  # ignore for local testing
  host: localhost
  password: redis_ws1
  db: 4
  port: 6379
postgresql:
  # ignore for local testing
  host: localhost
  port: 5432
  user: test
  password: test
  database: test
# mongodb:
#   host: localhost
#   port: 27017
#   user: root
#   password: example
#   database: test
authentication:
  standalone:
    application_secret_key: test
  mtbls_ws2:
    # ignore for local testing
    host: localhost
    port: 7007
    base_context_path: /metabolights/ws
    scheme: http
  keycloak:
    host: localhost:8080
    realm_name: master
    client_id: mtbls-ws3-test
    client_secret: "xxxx"
policy_service:
  opa:
    # ignore for local testing
    host_url: http://localhost:8181
system_health_check:
  remote:
    # ignore for local testing
    transfer_health_check:
      health_check_url: http://localhost:8081/health
  standalone:
    transfer_health_check:
      test: true
      test_response: true
mounted_paths:
  private_metadata_files_root_path: tests/data/storages/rw/studies/metadata-files
  deleted_private_metadata_files_root_path: tests/data/storages/rw/studies/deleted-files
  audit_files_root_path: tests/data/storages/rw/studies/audit-files
  internal_files_root_path: tests/data/storages/rw/studies/internal-files
  private_data_files_root_path: tests/data/storages/private-ftp/studies/data-files
  deleted_private_data_files_root_path: tests/data/storages/rw/studies/deleted-files
  report_files_root_path: tests/data/storages/rw/report-files
  public_studies_root_path: "tests/data/storages/public-ftp/study-files"
  deleted_public_studies_root_path: "tests/data/storages/public-ftp/deleted-study-files"
  indices_cache_root_path: tests/data/storages/rw/indices-cache
run:
  submission:
    port: 7077
    server_info:
      root_path: ""
    logging:
      level: DEBUG
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.rest_api.submission.log_filter.DefaultLogFilter
  common_worker:
    logging:
      level: DEBUG
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.worker.common.log_filter.DefaultLogFilter
  monitor:
    port: 5555
  cli:
    logging:
      level: DEBUG
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.cli.log_filter.DefaultLogFilter
